### PR TITLE
Kinetis MK66F18 and PJRC Teensy 3.6 support

### PR DESCRIPTION
**Pull request by walkerstop**
Teensy 3.6 support
Tested, USB working in the following modes:

FEI mode - 48 MHz with internal 32.768 kHz crystal
FEI mode - 96 MHz with internal 32.768 kHz crystal
PEE mode - 48MHz system clock driven by external crystal
PEE mode - 96MHz system clock driven by external crystal
PEE mode - 120MHz system clock driven by external crystal
PEE mode - 120MHz system clock driven by external crystal

### CODE REVIEW

**Comment by fpoussin** [comment]
Thank you! We'll have to merge #156 first.

**Comment by fpoussin** [comment]
Ready to merge?

**Comment by walkerstop** [comment]
I think so, I have not had a chance to test every driver on this mcu yet, is that ok? Is it ok to just submit future pull requests if I find something that needs to be corrected?

**Comment by fpoussin** [comment]
It's fine as long as it doesn't break anything else :)

**Comment by walkerstop** [comment]
In that case I think it's ready, if you were asking me

**Comment by fpoussin** [comment]
Alright, merging.

**Pull request merged**
