### PR TITLE
Add Tiva UART driver.

### PR DESCRIPTION
**Pull request by marcoveeneman**
This adds the UART driver for the Tiva series. It is tested on the TM4C123G launchpad.

I'll merge it no later than next week if there is no feedback. Any feedback is welcome :)

### CODE REVIEW

**Comment by fpoussin** [comment]
Looks good

**Comment by fpoussin** [comment]
You'll need to add "#define _CHIBIOS_RT_CONF_VER_5_0_" to chconf.h

**Comment by marcoveeneman** [comment]
@fpoussin I added the version tag to chconf.h

Since I opened this MR some time ago there were changes in chibios trunk which break compiling the demos. I'd like to address fixes for this in another branch, are you OK with this?

**Comment by fpoussin** [comment]
If you are going to fix them after merging this yes, otherwise you can open another pull request including the fixes or update this branch.

**Comment by marcoveeneman** [comment]
Yes i'll fix them in another branch after merging this one

**Pull request merged**
