### PR TITLE
Various Tiva improvements

### PR DESCRIPTION
**Pull request by marcoveeneman**
- Added events to PAL driver and removed EXT driver.
- Added multi target PAL teshal application.
- Fixed several build problems after changes in ChibiOS trunk.
- Updated all chconf.h, halconf.h and mcuconf.h files
- Fixed bug in pal_lld_writepad implementation
- Removed GPIO AHB/APB configuration for TM4C123x devices. AHB is now always used.

Can someone review this maybe? I realize this is quite a big PR, sorry for that :(

### CODE REVIEW

**Comment by fpoussin** [comment]
Hey,
How was this tested?

**Comment by marcoveeneman** [comment]
Hi, this was tested using the demos and pal testhal demo on both boards.

**Comment by fpoussin** [comment]
Gonna trust you with this one, thanks! :)

**Comment by marcoveeneman** [comment]
Thanks! I'll try to keep the next PRs a bit smaller ;)

**Pull request merged**
