### PR TITLE
Added New MCU Serial for WB32.

### PR DESCRIPTION
**Pull request by itarze**
Added New MCU Serial for WB32.

### CODE REVIEW

**Comment by itarze** [comment]
Can someone help me review this PR?

**Comment by itarze** [comment]
？

**Review by fpoussin — APPROVED** [review]

**Comment by fpoussin** [comment]
LGTM, but this will need to be added to CI for proper testing

**Comment by itarze** [comment]
> LGTM, but this will need to be added to CI for proper testing
Okay, I'll add it.

**Pull request merged**
