### PR TITLE
Added WB32 MCU GPIO current configuration

### PR DESCRIPTION
**Pull request by itarze**
Added WB32 MCU GPIO current configuration

### CODE REVIEW

**Comment by itarze** [comment]
Why did no one review it for so many days?

**Review by utzig — APPROVED** [review]
LGTM

**Comment by utzig** [comment]
> Why did no one review it for so many days?

I assume nobody works full time on this, and there's not that much free time. You may try to upstream this support to the main ChibiOS repo, Giovanni is a much better maintainer.

**Comment by itarze** [comment]
> > Why did no one review it for so many days?
> 
> I assume nobody works full time on this, and there's not that much free time. You may try to upstream this support to the main ChibiOS repo, Giovanni is a much better maintainer.

Okay, Thank you for reviewing my PR.

**Pull request merged**
