### PR TITLE
NUMICRO: Fix trivial but hard to find errors in USB LLD

### PR DESCRIPTION
**Pull request by elfmimi**
Fix:
- possible buffer overrun in usb_serve_out_endpoint()
- corner case src-dst confusion in usb_memcpy()

### CODE REVIEW

**Comment by elfmimi** [comment]
Plz merge this one prior to https://github.com/ChibiOS/ChibiOS-Contrib/pull/289 .

**Comment by alexclewontin** [comment]
~~I'm not sure I understand these changes. For example, the changes to usb_memcpy seem backwards to me. Can you explain why this is necessary?~~ 

~~Ah I see. There is definitely a mismatch between the order of the src and dest param between usb_memcpy.S and hal_lld_usb.c. However, I think if you want to correct this in usb_memcpy.S, you need to change it in multiple places. Maybe better to change the invocations in hal_lld_usb.c to match the existing order in usb_memcpy.S~~

Ah, wrong again. Sorry about that, it's late for me. The change to usb_memcpy.S looks correct. I'll look at it again tomorrow with fresh eyes, and maybe also suggest a couple of changes to the comments in the file.

**Review by alexclewontin — APPROVED** [review]
Changed a couple of erroneous comments in usb_memcpy.S. LGTM

**Comment by elfmimi** [comment]
Nice. My eyes were not seeing comments.

**Pull request merged**
