### PR TITLE
[HAL] [LPC11Uxx]: Add Initial Support for LPC11Uxx series

### PR DESCRIPTION
**Pull request by Codetector1374**
This PR add support to the LPC11Uxx series Cortex-M0 uControllers. 

- USB Support
- SPI Support
- Clock Configuration
- GPIO Support
- System Timer (ST) support

This also includes the correct linker script to produce the firmware checksum that LPC requires. This is a twos complement of the sum of the first 7 arm vector entry.

### CODE REVIEW

**Comment by Codetector1374** [comment]
I see the builds are failing. It doesn't seem to be introduced by my changes though. Let me know if there is anything I need to address before this PR can be accepted.

**Comment by fpoussin** [comment]
Hi, can you rebase your commits and add the platform to Jenkinsfile?

```
        stage('Build LPC') {
          agent {
            docker {
              image 'fpoussin/jenkins:ubuntu-18.04-chibios'
            }

          }
          steps {
            sh '''arm-none-eabi-gcc -v
cd $WORKSPACE/ext
for i in *.7z; do 7z x -y $i; done
cd $WORKSPACE
rm -rf $CH_PATH
git clone /var/lib/git/ChibiOS $CH_PATH
cd $CH_PATH
git remote set-url origin https://github.com/ChibiOS/ChibiOS.git
git fetch --all
git checkout -b $CH_BRANCH origin/$CH_BRANCH
git pull --rebase origin $CH_BRANCH
cd ext
for i in *.7z; do 7z x -y $i; done'''
            sh '''export CH_PATH=$WORKSPACE/ChibiOS
export CHC_PATH=$WORKSPACE
./tools/chbuild.sh ./demos/LPC/
'''
          }
        }
```

Thanks!

**Comment by fpoussin** [comment]
Ready to merge?

**Comment by Codetector1374** [comment]
Yeah should be. Looks like all CIs passed

**Comment by fpoussin** [comment]
CI didn't check your port because it's using the branch's file

**Review by fpoussin — APPROVED** [review]

**Comment by Codetector1374** [comment]
Oh I was wondering why I didn't see mine in the CI pipeline. But it all passes locally.

**Pull request merged**
