### PR TITLE
[WIP] Update to ChibiOS 18.2.x

### LINKED ISSUE #151: Platform.mk files should use their own SRC/INC variables
Now that ALLCSRC and ALLINC are defined, the platform.mk files should not append to PLATFORMSRC/INC. They should either create a new variable, or redefine PLATFORMSRC/INC, and then add the filenames to ALLCSRC, and ALLINC.

### PR DESCRIPTION
**Pull request by ObKo**
Fixes #151, inspired by https://github.com/ChibiOS/ChibiOS-Contrib/pull/152

What is already done:
- Smart build for HAL
- Separate makefiles for each LL driver (STM32)
- STM32 tests and demos updated to new Makefile format and RT-5.1 (ChibiOS 18.2.x) 

@utzig @fpoussin can you review this first changes, so I can move forward?

### CODE REVIEW

**Comment by fpoussin** [comment]
Hey,

This is a lot of changes for a single commit, can you split the changes so that it makes it easier to see what was changed?

Thanks!

**Comment by ObKo** [comment]
Sure

**Comment by ObKo** [comment]
```
testhal/STM32: 15 builds ok, 0 builds failed
FAIL: 
SKIPPED: 
```
```
demos/STM32: 3 builds ok, 0 builds failed
FAIL: 
SKIPPED: 
```
I will continue work for all other platforms then

**Comment by fpoussin** [comment]
Thanks!

**Pull request merged**
