### PR TITLE
Stm32 fixes

### PR DESCRIPTION
**Pull request by pl4nkton**

### CODE REVIEW

**Comment by fpoussin** [comment]
Can you add a check here: https://github.com/ChibiOS/ChibiOS-Contrib/pull/107/files#diff-e86bb84ff7328e855b605b232a081efeR1390 ?
In case the _STM32_OTG_STEPPING_ define is missing, we want to have a compiler error.
I assume this define would be located in _mcuconf_community.h_, don't forget to add it to _testhal/STM32/STM32F4xx/USB_HOST/mcuconf_community.h_

**Comment by pl4nkton** [comment]
The STM32_OTG_STEPPING is provided by the Chibios/RT HAL device registry.

**Comment by fpoussin** [comment]
Ok, are the QEI changes related to #84 ?

**Comment by pl4nkton** [comment]
Yes. But like sdalu comments in #84 some problems remain.

**Pull request merged**
