### PR TITLE
USBH: Various improvements

### PR DESCRIPTION
**Pull request by dismirlian**
Hi, these are some bug corrections and some improvements.

Some of them are:
- Added mechanism for out-of-tree class drivers. This will be probably improved further in the future.
- Added a workaround for an undocumented erratum in the STM32 OTG core (appears only with low speed devices).
- Improved robustness for STM32 OTG driver.
- HID: synchronization, minor bug correction.
- MSD: synchronization
- Various cleanups

Thanks,
Diego.

### CODE REVIEW

**Comment by fpoussin** [comment]
Excellent work, thanks!

**Comment by fpoussin** [comment]
Can you check why the build fails @dismirlian ?
http://jenkins.netyxia.net/job/ChibiOS-Contrib/53/console

Thanks

**Comment by dismirlian** [comment]
Hi @fpoussin, it fails because of the FATFS version used for the testhal example is 0.10b, and the build server is using 0.12b. I'll update the example to use the latest FATFS version.

Thanks,
Diego.

**Comment by dismirlian** [comment]
Hi @fpoussin, I think I have fixed the compile issue (https://github.com/dismirlian/ChibiOS-Contrib/tree/usbh_devel). Please tell me if you want me to submit another PR.

Thanks,
Diego.

**Comment by fpoussin** [comment]
Yes, please do.

**Pull request merged**
