### PR TITLE
[RP2040] Init USB out endpoints on transfer start

### PR DESCRIPTION
**Pull request by KarlK90**
@hanya I found an error in the USB driver, when starting new out transfers the out endpoint has to be configured immediately or otherwise a data sequence error is generated. The actual fix is on line 873 in `usb_lld_start_out()` Could you confirm / review my changes? 

The only notable other change was the condition for detecting an short package, which in my understanding is only the case if the transfer length is under 64 Byte? Also `rxpkts` is an unsigned integer so can never be smaller than 0, therefore I changed the check to equals.

With these changes QMK successfully enumerates with the HID descriptors.

### CODE REVIEW

**Comment by hanya** [comment]
Looks good for me. Thank you finding the problem in the driver.

**Comment by KarlK90** [comment]
> Looks good for me. Thank you finding the problem in the driver.

Great! :slightly_smiling_face: 

@fpoussin feel free to merge on your approval!

**Review by fpoussin — APPROVED** [review]

**Comment by fpoussin** [comment]
LGTM, thanks!

**Comment by KarlK90** [comment]
Great! Thanks for the merge!

**Pull request merged**
