### PR TITLE
SAMD21: Adding Initial Support for SAMD21A

### PR DESCRIPTION
**Pull request by minh7a6**
Currently the following features has been implemented:
- ADC without DMA (need more testing)
- SPI with DMA
- I2C Master (up to 400kHz for now)
- SIO
- GPIO

### CODE REVIEW

**Comment by fpoussin** [comment]
Could you add it to the Github workflow for build validation?

**Comment by minh7a6** [comment]
I have updated the Github Workflow

**Comment by fpoussin** [comment]
> I have updated the Github Workflow

`ChibiOS-Contrib/ChibiOS-stable_21.11.x/os/hal/include/hal_sio.h:471:3: error: unknown type name 'sio_events_mask_t'; did you mean 'eventmask_t'?
`

**Comment by minh7a6** [comment]
Hmm, I think I might have written my SIO driver based on the latest master instead of stable_21.11.x . I'll see if I can make this comply with the stable branch instead of master

**Comment by minh7a6** [comment]
I've fixed the SIO now as well as including the new features for the samd21. Can you approve the workflow?

**Review by fpoussin — APPROVED** [review]

**Comment by fpoussin** [comment]
LGTM, thank you! :)

**Pull request merged**
