### PR TITLE
USBH updates

### PR DESCRIPTION
**Pull request by dismirlian**

### CODE REVIEW

**Comment by dismirlian** [comment]
Hi, I'm pushing changes so it compiles again. I had tested against ChibiOS master, instead of 18.2.x.

**Comment by fpoussin** [comment]
I needs to be compatible with 19.x, can you update the chconf files?
It was using the correct files but you reverted them in 2644acd for some reason.

**Comment by dismirlian** [comment]
It failed to compile because Jenkins is using 18.2.x, so I updated the demos to 18.2.x, right?

**Comment by dismirlian** [comment]
> Edit: I forgot jenkins was compiling against 18.x, I've updated it to use 19.x
I think this may break all of the examples.

**Comment by fpoussin** [comment]
> > Edit: I forgot jenkins was compiling against 18.x, I've updated it to use 19.x
> > I think this may break all of the examples.

Yes, I'll fix those then you can merge master.

**Comment by fpoussin** [comment]
Actually your branch passes CI, can you still replace the conf files with the latest version?

**Comment by fpoussin** [comment]
@dismirlian You can merge master.

**Comment by fpoussin** [comment]
Let me know when it's ready to merge, or feel free to merge it yourself :)

**Comment by dismirlian** [comment]
Hi @fpoussin, it's ready to merge; I think I don't have write access so I can't do it myself.

Thanks for your hard work!

Cheers,
D.

**Pull request merged**
