### PR TITLE
NUMICRO: add I2C driver

### PR DESCRIPTION
**Pull request by elfmimi**
Add NUMICRO I2C driver
Redoing https://github.com/ChibiOS/ChibiOS-Contrib/pull/234 .

### CODE REVIEW

**Comment by fpoussin** [comment]
Can you add a test in testhal for this driver? Thanks!

**Comment by elfmimi** [comment]
Seems it's still half baked. I'll try to mash-up a test, or maybe more like example, for this. and fix here and there on the way.

**Comment by elfmimi** [comment]
WIP

**Comment by elfmimi** [comment]
Based off of new NUC123 basis.

**Comment by fpoussin** [comment]
Let me know when it's ready for review :)

**Comment by elfmimi** [comment]
This should be acceptable as a starting point. Could you start reviewing? @fpoussin
Tested successfully on an actual NUTINY-SDK-NUC123-V2.0 dev board.

**Review by fpoussin — DISMISSED** [review]

**Comment by elfmimi** [comment]
Oops, I forgot one more thing to include.

**Review by fpoussin — DISMISSED** [review]

**Comment by elfmimi** [comment]
Here is comparison views of today's two force pushs, for your convenience.
https://github.com/elfmimi/ChibiOS-Contrib/compare/d38e505..311bb03
https://github.com/elfmimi/ChibiOS-Contrib/compare/311bb03..be7fdd1

**Comment by elfmimi** [comment]
the change in os/hal/ports/NUMICRO/LLD/SERIALv1/hal_serial_lld.c is unintentional.
I was to do it separately. but this is a correct correction. so I'll keep it unless reviewers suggest separation.

**Comment by elfmimi** [comment]
Sorry for annoyance with repeated force push.
Took back unintended change I mentioned in above comment. https://github.com/ChibiOS/ChibiOS-Contrib/pull/235#issuecomment-754686256
Added proactive support for NUC123xxxAEx variants.

**Comment by elfmimi** [comment]
I think it's ready to merge.

**Review by fpoussin — APPROVED** [review]

**Comment by fpoussin** [comment]
Thanks!

**Pull request merged**
