### PR TITLE
NUMICRO: bunch of small fixes

### PR DESCRIPTION
**Pull request by elfmimi**
It seems there are still many places which need my attention.
feel free to squash this at your disposal.

### CODE REVIEW

**Comment by elfmimi** [comment]
@alexclewontin Hey, you might want to review these changes. Won't you?

**Review by fpoussin — DISMISSED** [review]

**Comment by fpoussin** [comment]
@elfmimi I've invited you and @alexclewontin to contributors, you should be able to review/merge PRs as long as they pass the build tests.

**Comment by elfmimi** [comment]
> you should be able to review/merge PRs as long as they pass the build tests.

I believe we don't have that permission yet.

**Comment by fpoussin** [comment]
@elfmimi did you retry?

**Review by fpoussin — APPROVED** [review]

**Comment by elfmimi** [comment]
I got affirmative response from the only user of NUMICRO port I know, stating that this PR does not break his build. so I'll gonna merge this. Let's address to inconveniences as we run into them if any, and let us move on.

**Pull request merged**
