### PR TITLE
Feature/lld can support for stm32g4xx fdcan nucleo32

### PR DESCRIPTION
**Pull request by julienrhodes**
I implemented a CANv2 driver which currently only supports the FDCAN peripheral on STM32G micro-controllers. There was deliberation over the best naming (FDCANv1 vs CANv2). In the end, CANv2 seems more flexible (unified architecture for bxCAN 2.0 and FDCAN would be possible) and more appropriate (FDCAN periphs can send CAN 1.0 frames after-all!). This is not extensively tested, but does seem to work on the internal loopback. I will test with an actual CAN bus soon.

### CODE REVIEW

**Comment by fpoussin** [comment]
Hi,

Build has failed, please fix it.
It has to build against 19.1.x

```
BUILDING: ./demos/STM32/RT-STM32G431KB-NUCLEO32-CAN
Makefile:101: /home/jenkinsremote/workspace/ChibiOS-Contrib_PR-207@2/ChibiOS/os/common/startup/ARMCMx/compilers/GCC/mk/startup_stm32g4xx.mk: No such file or directory
/home/jenkinsremote/workspace/ChibiOS-Contrib_PR-207@2/os/hal/ports/STM32/STM32G4xx/platform.mk:36: /home/jenkinsremote/workspace/ChibiOS-Contrib_PR-207@2/ChibiOS/os/hal/ports/STM32/LLD/RTCv3/driver.mk: No such file or directory
Makefile:106: /home/jenkinsremote/workspace/ChibiOS-Contrib_PR-207@2/ChibiOS/os/hal/osal/rt-nil/osal.mk: No such file or directory
make: *** No rule to make target '/home/jenkinsremote/workspace/ChibiOS-Contrib_PR-207@2/ChibiOS/os/hal/osal/rt-nil/osal.mk'.  Stop.
```

Thanks you

**Comment by julienrhodes** [comment]
Well that's a bit of a conundrum. This depends on STM32G logic which is in master of ChibiOS-RT, but not in 19.1.X stable. It is my understanding that the path to ChibiOS-RT is through Contrib. What do you recommend? I don't think it is right for me to backport the changes from master of RT into contrib just to make this contribution work, do you?

**Comment by fpoussin** [comment]
There is no pulling to RT, as the owner still uses SVN... (😢) and only accept patches. The GH repo is just a mirror.
Most of the stuff in Contrib will never be merged in RT/Hal as it's not tested enough, or too specific. (there were exceptions such as DAC)
I would recommend to ask for a backport of the G4 support to stable branches, then we can merge it.
20.x.x is probably not far away anyway.

**Comment by fpoussin** [comment]
Hi,
Now that 20.3.x is out and Contrib has been updated for it, this could probably get merged via a new pull request.

**Pull request closed without merging**
