### PR TITLE
Sonix SN32 series support

### LINKED ISSUE #225: Add SN32F248B Support
Here is the details of this MCU: http://www.sonix.com.tw/article-en-4336-30356

Thanks for help!

### PR DESCRIPTION
**Pull request by dexter93**
Preliminary support for SONIX SN32F2XX series

Supports most 32bit SONIX [chips](https://www.sonix.com.tw/category-en-947). Includes native ChibiOS drivers for the most part and placeholders using reference code for the not-yet-implemented ones. Still under development, but having them in a common -Contrib will improve portability and aid future development

Closes https://github.com/ChibiOS/ChibiOS-Contrib/issues/225

### CODE REVIEW

**Comment by dexter93** [comment]
platform test beds: SN32F240B, SN32F260 ( mostly) and SN32F240. SN32F240 gets it's own LLD since it has significant hardware differences to other F2XX chips. This has been tested to work reliably so far with QMK at SonixQMK repos.

**Comment by fpoussin** [comment]
Hi!
Can you add this platform to the CI for testing?
Thanks

**Comment by dexter93** [comment]
> Hi! Can you add this platform to the CI for testing? Thanks

Hi there. Probably, but I see that CI uses testhal and demos requiring not yet implemented drivers ( I2C,ADC, UART - most of those are out of scope since no device with them is using them on QMK so far). Could you specify what is needed for CI? Thanks!

**Comment by fpoussin** [comment]
You need to have at least one _testhal_ folder and add it to the CI.
You're free to chose which drivers to test.

**Comment by jindaxia** [comment]
Great Job!

**Pull request merged**
