### PR TITLE
[KINETIS] Move from main repo to contrib

### PR DESCRIPTION
**Pull request by utzig**
@barthess Please don't merge this. This is for testing purposes right now.

### CODE REVIEW

**Comment by utzig** [comment]
Fixed, thanks!

**Comment by barthess** [comment]
Why it was moved?

**Comment by utzig** [comment]
The port has been stale on the main repo for quite a long time and there are already many developments in personal repos on Github. Hopelessly moving it here may give it some breath to continue evolving.

**Comment by utzig** [comment]
Will merge this because otherwise it will be impossible to review the next Kinetis pull request.

**Pull request merged**
