### PR TITLE
Added WB32F3G71xx support

### PR DESCRIPTION
**Pull request by itarze**
WB32F3G71xx series MCU is designed by Westberry Technology.

### CODE REVIEW

**Comment by utzig** [comment]
@wb-Joy Where can I find the datasheet and reference manual for the F3 family?

**Comment by itarze** [comment]
@utzig The following is the download link of the manual:
rm: http://www.westberrytech.com/down/20210903/WB32F3G71xx%20reference%20manual%20v01.pdf
ds: http://www.westberrytech.com/down/20210903/WB32F3G71-DS.pdf

**Comment by itarze** [comment]
@utzig  Has the review been completed? Can merge my PR?

**Review by utzig — APPROVED** [review]
LGTM

**Pull request merged**
