### PR TITLE
Refactor NRF51 RTC code to reduce duplication, style fixes

### PR DESCRIPTION
**Pull request by utzig**
@sdalu I did some refactoring to the NRF51 RTC code. Please do a review do see if there's any problem or if you agree with the changes.

### CODE REVIEW

**Comment by sdalu** [comment]
* I would suggest inlining the static function as there can only have one RTC0 or RTC1
* I find it a bite confusing to nest NRF51_ST_USE_RTC0 / OSAL_ST_MODE for function and OSAL_ST_MODE / NRF51_ST_USE_RTC0 for IRQ

**Comment by utzig** [comment]
> I find it a bite confusing to nest NRF51_ST_USE_RTC0 / OSAL_ST_MODE for function and OSAL_ST_MODE / NRF51_ST_USE_RTC0 for IRQ

You mean between helper functions and main functions in init/irqs?

**Comment by sdalu** [comment]
Yes. That's just I got lost when reading IRQ handler, because my mind was used to the NRF51_ST_USE_RTC0 / OSAL_ST_MODE order used in the first part of the file.

**Comment by sdalu** [comment]
I realize that `hal_lld_init.c` should be fixed
~~~
#if (OSAL_ST_MODE != OSAL_ST_MODE_NONE) &&                      \
    ((NRF51_ST_USE_RTC0 == TRUE) || (NRF51_ST_USE_RTC1 == TRUE))
  NRF_CLOCK->TASKS_LFCLKSTART = 1;
#endif
~~~

**Comment by sdalu** [comment]
@utzig shouldn't it be closed?

**Comment by utzig** [comment]
Yes, I'll close it because it's just a refactoring. This started to have conflicts when RTC1 support was added. I may update it in the future or not...

Thanks!

**Pull request closed without merging**
