### PR TITLE
Nuvoton NUC123SD4AN0 MCU port

### PR DESCRIPTION
**Pull request by fishman**
This is the original patch @GitWellBack made for the Nuvoton MCU

"Drivers and requisite CMSIS files included. Original manufacturer copyright notices have naturally been kept for files directly from there."

### CODE REVIEW

**Comment by fishman** [comment]
@fpoussin @stapelberg any hints on how i can get this merged?

**Comment by fpoussin** [comment]
Hi! Can you rebase? I've fixed CI.
Thanks

**Review by fpoussin — APPROVED** [review]

**Comment by fpoussin** [comment]
I've merged it since it has no tests anyway, feel free to open a PR with tests, thanks!

**Comment by fishman** [comment]
Awesome thanks, I'll try to add some.

**Pull request merged**
