### PR TITLE
Adding new board called EdgePro1 based on MIMXRT1064

### PR DESCRIPTION
**Pull request by jturnsek**
EdgePro1 is a new board based on i.MXRT1064 CPU and Nina W102 communication module. It is used for general IoT development and EdgeProMX mechanical keyboard.

Description
New board EdgePro1 added
BSP for MIMXRT1064 added

Tested on EdgeProMX hardware.

### CODE REVIEW

**Comment by davidbuzz** [comment]
just curious.. how similar is this to the Teensy4 board, which is a RT1062 ?

**Comment by jturnsek** [comment]
> just curious.. how similar is this to the Teensy4 board, which is a RT1062 ?

It is similar in size, but has additional more Flash memory (4MB and 8MB), WiFi/BLE module, RGB LED, ...

**Review by fpoussin — APPROVED** [review]

**Comment by fpoussin** [comment]
Lots of nice work here, thank you!

**Comment by davidbuzz** [comment]
I'm still waiting to see LLD drivers for dma, spi, and i2c*[this pr, thx] before I'm going to be able to use any of the imx port/s in 'anger'. :-)

**Pull request merged**
