### PR TITLE
reviving 24 series eeprom

### PR DESCRIPTION
**Pull request by rusefillc**
1) handling API change ``fileoffset_t *offset`` parameter
2) extern C for C++ invocation

### CODE REVIEW

**Review by fpoussin — CHANGES_REQUESTED** [review]
Changing mcux submodule is a no go

**Comment by fpoussin** [comment]
`/home/runner/work/ChibiOS-Contrib/ChibiOS-Contrib/os/hal/src/hal_ee25xx.c:380:22: error: too few arguments to function 'eepfs_getposition'
`

**Comment by fpoussin** [comment]
testhal/demos needs to be updated

**Review by fpoussin — APPROVED** [review]

**Comment by fpoussin** [comment]
Thanks!

**Comment by rusefillc** [comment]
@fpoussin please note source branch name "rusefi-20.3.x" please cherry-pick this to 20.3.x branch?

**Pull request merged**
