### PR TITLE
HAL AVR USB device driver support

### PR DESCRIPTION
**Pull request by rlippert**
This PR adds an interrupt-driven USB device mode driver to the AVR port similar to the existing STM32 USB implementation. No support for USB host mode or OTG at this time as I don't have any AVR chips to use that support those modes.

Includes a demo app and board definition so that the functionality can be quickly tested against a PJRC Teensy2++ board (http://pjrc.com/store/teensypp.html).

### CODE REVIEW

**Comment by utzig** [comment]
Wouldn't it be better to contribute this to the official repo since the AVR port is there?

**Comment by rlippert** [comment]
I originally tried that but it got rejected: https://github.com/ChibiOS/ChibiOS/pull/11

I think there are copyright and support issues with the official repo, the owner seems to only like to submit self-created code or small fixes from community.

**Comment by utzig** [comment]
Make a patch with the same contents as this pull request against the main repo and I will apply it. Going through github doesn't really make any sense for the main repo because it's just a read-only mirror.

**Comment by rlippert** [comment]
I've attached a patchset reworked against the main SVN codebase as a gist here: https://gist.github.com/rlippert/f6ab7b56a8e4e6e3eb094f340970bee9

**Comment by utzig** [comment]
This was applied against the main repo so I'm closing here. Great work btw!

**Pull request closed without merging**
